#pragma once

#include <string>
#include <vector>
#include <mutex>
#include <nlohmann/json.hpp>

struct ClusterNode {
    std::string id;           // Unique ID generated by the child (or assigned by parent)
    std::string ip_address;   // IP address (with port) of the child node
    std::string status;       // "pending", "connected", "offline"
    std::string hostname;
    std::string platform;
    std::string master_token;     // Generated by parent for this child to use
    std::string encryption_key;   // Unique key for hashing payload
    long last_seen;
};

class ClusterManager {
public:
    static ClusterManager& GetInstance() {
        static ClusterManager instance;
        return instance;
    }

    // Initialize or load nodes
    void LoadNodes();
    void SaveNodes();

    // Register a new incoming connection request
    bool RegisterNodeRequest(const std::string& id, const std::string& ip_address, const std::string& hostname, const std::string& platform);
    
    // Admin action: approve a node
    bool ApproveNode(const std::string& id);
    
    // Admin action: remove or deny a node
    void RemoveNode(const std::string& id);

    // Get list of nodes
    std::vector<ClusterNode> GetNodes();
    
    // Get a specific node
    bool GetNode(const std::string& id, ClusterNode& out_node);

    // Update last seen timestamp
    void PingNode(const std::string& id);

    bool UpdateNodeId(const std::string& oldId, const std::string& newId);
    bool SetNodeStatus(const std::string& id, const std::string& status);

private:
    ClusterManager() {}
    std::vector<ClusterNode> nodes;
    std::mutex mtx;
};
